version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    shm_size: '4gb'
    environment:
      #- POSTGRES_HOST_AUTH_METHOD=trust                   # If you set POSTGRES_HOST_AUTH_METHOD to trust, then POSTGRES_PASSWORD is not required.
      - POSTGRES_USER=root                                 # set your container root username
      - POSTGRES_PASSWORD=secret                           # set your container root password
      - POSTGRES_DB=A5bark-docker       # set your container database name
    ports:
      - 5432:5432
    networks:
      - A5bark
    volumes:
      - postgres:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com              # set your container default email
      - PGADMIN_DEFAULT_PASSWORD=secret                    # set your container default password
    ports:
      - 5050:80
    networks:
      - A5bark
    volumes:
      - pgadmin:/var/lib/pgadmin

networks:
  A5bark:
    name: A5bark-network

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
